# .gitlab-ci.yml
stages:
  - format_check
  - build_test_deploy

variables:
  GCC_FLAGS: "-Wall -Werror -g"

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - /var/cache/apt/archives/
  policy: pull-push

include:
  - local: ".gitlab/workflows/format_check.yml"
  - local: ".gitlab/workflows/build_test_deploy.yml"
