name: CI - Clang Tidy Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  clang-tidy:
    name: Syntax Check und Clang-Tidy
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Abhängigkeiten installieren
        run: |
          sudo apt-get update
          sudo apt-get install -y clang clang-tidy

      - name: Syntax Check durchführen
        run: |
          find . -name "*.c" | xargs -r clang -fsyntax-only -Wall -Wextra

      - name: Clang-Tidy ausführen
        run: |
          find . -name "*.c" | xargs -I {} clang-tidy {} -- -std=c99