name: C CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential valgrind gcc

      - name: Build Project
        run: |
          make CC=gcc CFLAGS="-Wall -Werror -g"

      - name: Make Executable
        run: chmod +x ./bin/sysprak-client

      - name: Run Valgrind and Collect Output
        run: |
          valgrind_output=$(valgrind --leak-check=full --track-origins=yes ./bin/sysprak-client -g 1234567890123 -p 1 2>&1 || true)
          echo "$valgrind_output" > valgrind.log

      - name: Analyze Valgrind Output
        run: |
          cat valgrind.log
          if grep -q "ERROR SUMMARY: [^0]" valgrind.log; then
            echo "Memory leaks detected"
            exit 1
          else
            echo "No memory leaks detected"
          fi

      - name: Deploy if Tests Pass
        if: ${{ success() }}
        run: |
          # Add your deployment commands here
          echo "Deploying application..."
