name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Update Package Lists
        run: sudo apt-get update
      - name: Install Required Tools
        run: |
          sudo apt-get install -y clang clang-format clang-tidy
      - name: Cache Installed Tools (Optional)
        run: echo "Dependencies installed" # Placeholder for caching

  clang-format:
    name: ClangFormat
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run ClangFormat
        run: |
          find neunermuehle-client -name "*.c" -o -name "*.h" \
            | xargs -r clang-format -style=file --assume-filename=neunermuehle-client/.clang-format --dry-run --Werror

  syntax-check:
    name: Syntax Check
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run Syntax Check
        run: |
          find neunermuehle-client -name "*.c" \
            | xargs -r clang -fsyntax-only -Wall -Wextra

  clang-tidy:
    name: Clang-Tidy
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run Clang-Tidy
        run: |
          find neunermuehle-client -name "*.c" \
            | xargs -I {} clang-tidy {} --config-file=neunermuehle-client/.clang-tidy -- -std=c99
