name: Shared Memory Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_run:
    workflows: ["Build Project"]
    types:
      - completed

jobs:
  shared-memory-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install required dependencies including clang
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential valgrind clang

      # Step 3: Compile the shared memory test (if not already built)
      - name: Compile Shared Memory Test
        run: |
          gcc -Wall -Werror -g -o ./tests/test_sharedMemory/test_sharedMemory \
            ./tests/test_sharedMemory/test_sharedMemory.c \
            ./modules/shared_memory/shared_memory.c \
            -I./modules/shared_memory

      # Step 4: Run the shared memory test
      - name: Run Shared Memory Test
        run: |
          chmod +x ./tests/test_sharedMemory/test_sharedMemory
          ./tests/test_sharedMemory/test_sharedMemory