name: Valgrind Memory Leak Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  valgrind-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install required dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential valgrind

      # Step 3: Compile the shared memory test
      - name: Compile Shared Memory Test
        run: |
          gcc -Wall -Werror -g -o ./tests/test_sharedMemory/test_sharedMemory \
            ./tests/test_sharedMemory/test_sharedMemory.c \
            ./modules/shared_memory/shared_memory.c \
            -I./modules/shared_memory

      # Step 4: Run the shared memory test (ohne Valgrind)
      - name: Run Shared Memory Test
        run: |
          chmod +x ./tests/test_sharedMemory/test_sharedMemory
          ./tests/test_sharedMemory/test_sharedMemory

      # Step 5: Apply Valgrind to the shared memory test (mit Timeout)
      - name: Run Valgrind on Shared Memory Test
        run: |
          chmod +x ./tests/test_sharedMemory/test_sharedMemory
          timeout 240 valgrind --leak-check=full --track-origins=yes ./tests/test_sharedMemory/test_sharedMemory 2>&1 | tee valgrind_shared_memory.log
          EXIT_CODE=$?

          # Prüfen, ob timeout das Programm abgebrochen hat
          if [ $EXIT_CODE -eq 124 ]; then
            echo "Valgrind timed out on Shared Memory Test"
            exit 1
          fi

      # Step 6: Analyze Valgrind output for the shared memory test
      - name: Analyze Valgrind Output for Shared Memory Test
        run: |
          cat valgrind_shared_memory.log
          if grep -q "ERROR SUMMARY: [^0]" valgrind_shared_memory.log; then
            echo "Memory leaks detected in shared memory test"
            exit 1
          else
            echo "No memory leaks detected in shared memory test"
          fi

      # Step 7: Compile the main project (Beispiel über Makefile)
      - name: Build Project
        run: |
          make CC=gcc CFLAGS="-Wall -Werror -g"

      # Step 8: Make the main executable file executable
      - name: Make Executable
        run: chmod +x ./bin/sysprak-client

      # Step 9: Apply Valgrind to the main executable (mit Timeout)
      - name: Run Valgrind on Main Executable
        run: |
          timeout 240 valgrind --leak-check=full --track-origins=yes ./bin/sysprak-client -g 1234567890123 -p 1 2>&1 | tee valgrind.log
          EXIT_CODE=$?

          if [ $EXIT_CODE -eq 124 ]; then
            echo "Valgrind timed out on Main Executable"
            exit 1
          fi

      # Step 10: Analyze Valgrind output for the main executable
      - name: Analyze Valgrind Output for Main Executable
        run: |
          cat valgrind.log
          if grep -q "ERROR SUMMARY: [^0]" valgrind.log; then
            echo "Memory leaks detected in main executable"
            exit 1
          else
            echo "No memory leaks detected in main executable"
          fi
